### ISSUE TITLE
ciede2000 algorithm is not corectly implemented.

### ISSUE THREAD

**Issue by guddas** [markusn/color-diff#10]
your implementation of the ciede2000 algorithm doesn't return the correct value.

**examples:** 

![here](http://i.imgur.com/2bY6G5T.png)

**Comment by markusn** [comment]
Sorry I can't see the problem, for each pair what is the expected difference output?

**Comment by guddas** [comment]
pardon me, it was me who calculated the wrong value not your implementation of the algorithm.
