### ISSUE TITLE
Allow lowercase RGB objects as input

### ISSUE THREAD

**Issue by evelynhathaway** [markusn/color-diff#17]
Many libraries ([tinycolor](https://github.com/bgrins/TinyColor) for instance) and codebases use `{r, g, b}` objects to represent RGB colors instead of the currently supported `{R, G, B}`.

Would be open to a PR adding support for the lowercase keys?

**Comment by markusn** [comment]
@evelynhathaway yes! do a PR and I'll merge it, I missed this issue for some reason

**Comment by evelynhathaway** [comment]
Added a PR based on `master`
