### ISSUE TITLE
Support alpha transparency?

### ISSUE THREAD

**Issue by ben-eb** [markusn/color-diff#8]
It would be really great if this could support colour difference via alpha channel, like this lib written in PHP. :smile: https://github.com/donatj/AlikeColorFinder

**Comment by markusn** [comment]
I looked at the implementation and I am a not convinced it is suitable for this library. As far as I can see the addition is that abs(c1_alpha - c2_alpha) * 255 is added to the ciede2000 difference. My understanding is that an alpha value of 0.0 means that the color is completely transparent; two colors with alpha 0.0 are visually the same (they aren't visible) hence the difference should be 0.0. But with the above implementation they will have the difference of the colors disregarding the alpha channel, i.e. the difference does not reflect the visual perception of the colors given the alpha channel.

Instead I have implemented a solution where each RGBA color is transformed into an RGB color before being used to calculate the CIEDE2000 difference. This is done by blending the color into the background color (defaults to white but can be changed using an argument to the function) given the alpha channel (0.0-1.0). Please try it out, it is part of the master branch and is not yet published on npmjs.org. Hope the solution is sufficient for your use-case!

**Comment by markusn** [comment]
I will close this issue, please submit a bug report if you find any errors.

**Comment by ben-eb** [comment]
Awesome, thank you for the fast response. The use case is handling alpha transparency for colorguard (https://github.com/SlexAxton/css-colorguard#alpha-transparency). :smile:

**Comment by markusn** [comment]
Ok, sounds interesting, hope it works out :)

**Comment by markusn** [comment]
Did you implement this feature? I'm considering making a new release of color-diff and it would be interesting to know if the functionality was sufficient.

**Comment by ben-eb** [comment]
Haven't got around to it yet unfortunately, been super busy.

**Comment by markusn** [comment]
Ok. The alpha-channel support is part of version 1.0.0 that was just published on npm.
