### ISSUE TITLE
Migrate to ES6 / ES2015?

### ISSUE THREAD

**Issue by marcobiedermann** [markusn/color-diff#9]
What do you think about migrating the project to ES2015?

**Comment by markusn** [comment]
Hi! I am not familiar with the status of ES6 on nodejs, are there any benefits (especially in performance)?

**Comment by marcobiedermann** [comment]
@markusn Using native ES2015 functions instead of your own will always be faster e.g. `import` vs `require`. Also with `const`the interpreter can assign memory more efficiently.
With ES2015 you code might look cleaner for you and the parser to read.

**Comment by markusn** [comment]
It seems interesting as it is possible to transpile to ES5 for backward compatibility for users of older versions of node. However I will not likely have time to implement this in the near future, but would happily take a pull-request.

**Comment by valmynd** [comment]
did a pull request, see #12

**Comment by evelynhathaway** [comment]
@markusn, were you thinking of a build step and traspiling down to ES5? I'm down to help migrate to ES6+

**Comment by markusn** [comment]
Hi! I'm going to do a 2.0.0 with ES6 (no transpiling to ES5).

**Comment by evelynhathaway** [comment]
Awesome! Let me know if there's anything I can do to help. I've already changed `var` to `let` and `const` where appropriate in a fork (see commit: https://github.com/markusn/color-diff/commit/5624aaea7d2eb06305882d059eddea765ba64a75) in case you want to rebase it or I can create a PR for it. 😄

**Comment by justinfagnani** [comment]
Any news here? I'd love to use this in a client-side JS modules only project. I can help port too.

**Comment by markusn** [comment]
@justinfagnani I have a PR open to solve this: https://github.com/markusn/color-diff/pull/22 . Would that work for you?
